sequenceDiagram
    participant przeglądarka
    participant serwer

    przeglądarka->>serwer: GET https://studies.cs.helsinki.fi/exampleapp/spa
    activate serwer
    serwer-->>przeglądarka: dokument HTML
    deactivate serwer

    przeglądarka->>serwer: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    activate serwer
    serwer-->>przeglądarka: plik CSS
    deactivate serwer

    przeglądarka->>serwer: GET https://studies.cs.helsinki.fi/exampleapp/spa.js
    activate serwer
    serwer-->>przeglądarka: plik JavaScript
    deactivate serwer

    Note right of przeglądarka: Przeglądarka wykonuje kod JavaScript i pobiera dane JSON

    przeglądarka->>serwer: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate serwer
    serwer-->>przeglądarka: [{ "content": "klasa", "date": "2023-1-1" }, ... ]
    deactivate serwer

    Note right of przeglądarka: Przeglądarka renderuje notatki dynamicznie na stronie

    Note right of przeglądarka: Użytkownik wpisuje nową notatkę i klika przycisk "Save"

    przeglądarka->>serwer: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa
    activate serwer
    serwer-->>przeglądarka: Status odpowiedzi (np. 201 Created)
    deactivate serwer

    Note right of przeglądarka: Przeglądarka aktualizuje listę notatek bez przeładowania strony
