sequenceDiagram
    participant przeglądarka
    participant serwer

    przeglądarka->>serwer: GET https://studies.cs.helsinki.fi/exampleapp/spa
    activate serwer
    serwer-->>przeglądarka: czyta html
    deactivate serwer

    przeglądarka->>serwer: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    activate serwer
    serwer-->>przeglądarka: czyta css
    deactivate serwer

    przeglądarka->>serwer: GET https://studies.cs.helsinki.fi/exampleapp/spa.js
    activate serwer
    serwer-->>przeglądarka: czyta JS
    deactivate serwer

    Note right of przeglądarka: pobiera dane json z serwera

    przeglądarka->>serwer: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate serwer
    serwer-->>przeglądarka: [{ "content": "", "date": "2023-1-1" }, ... ]
    deactivate serwer

    Note right of przeglądarka: wczytuje notatki bez przeładowania strony "robi to za pomoca JSa"
